"""fix additionalneeds type

Revision ID: 3f9a9f57cf04
Revises: c8c9d262fc29
Create Date: 2026-07-30 17:51:34.502442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9a9f57cf04'
down_revision: Union[str, None] = 'c8c9d262fc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
