"""fix additionalneeds type x2

Revision ID: c2acceb508e2
Revises: 3f9a9f57cf04
Create Date: 2026-07-30 17:52:24.359761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2acceb508e2'
down_revision: Union[str, None] = '3f9a9f57cf04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'additionalneeds',
               existing_type=sa.DATE(),
               type_=sa.String(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'additionalneeds',
               existing_type=sa.String(length=200),
               type_=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
